spring:
  profiles:
    active: ${PROFILES_ACTIVE}

  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true

logging:
  level:
    root: INFO
